# Generated by Django 4.1 on 2023-11-26 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="note/img/"),
        ),
    ]
